### PR TITLE
[sslcertificates] Add issuer name as label

### LINKED ISSUE #166: sslcertificates: Add issuer as label
Currently the plugin adds the issuer hash as label, which has two disadvantages:

1. As the issuer hash for let's encrypt changes from time to time (e.g. https://letsencrypt.org/2024/04/12/changes-to-issuance-chains.html), the rule for setting shorter WARN/CRIT has a growing number of hashes. With plain text issuers that list could become shorter by using regex and self-describing.
2. The hash doesn't work on Windows (also see https://github.com/HeinleinSupport/check_mk_extensions/issues/116#issuecomment-1381485095), so it's not possible to set different rules for different issuers.

Latter is required as let's encrypt are auto-renewed ~30 days before expiration, while others need manual renewal and 30 days might be too short for that.

### PR DESCRIPTION
**Pull request by mueller-ma**
Closes #166

### CODE REVIEW

**Comment by mueller-ma** [comment]
I tested this in my Checkmk installation with one Linux and one Windows agent and it works fine:

grafik

**Comment by gurubert** [comment]
Please change the pull request. You also added a loop to read certificates from the current user's cert store. This will not be accepted.

**Comment by mueller-ma** [comment]
The code https://github.com/HeinleinSupport/check_mk_extensions/blob/cmk2.3/sslcertificates/agents/windows/plugins/sslcertificates.ps1#L7-L19 is equal to https://github.com/HeinleinSupport/check_mk_extensions/blob/cmk2.3/sslcertificates/agents/windows/plugins/sslcertificates.ps1#L23-L35. Only the argument of `Get-ChildItem` is different. I didn't want to add my new code twice, so I add a loop and de-duplicated code.
I can undo that change, but IMO the code quality is improved by that.

**Comment by gurubert** [comment]
Please create a second pull request for such a change. Otherwise changes are not understandable.

**Comment by mueller-ma** [comment]
I rebase this PR once #171 is merged.

**Comment by gurubert** [comment]
PR #171 has been merged.

**Comment by mueller-ma** [comment]
Rebase done. The change in the Powershell script is now minimal.

**Pull request merged**
