### PR TITLE
Infortend plugin compatibility rework

### PR DESCRIPTION
**Pull request by jens-maus**
This PR is a slight rework of the infortrend check mk extension to incorporate the following changes:

- compatibility to CheckMK 2.3.0+ with its deprecation of the oldest checkmk plugin API. Now `LegacyCheckDefinition` is used which is still compatible with CheckMK 2.0.0 up to 2.3.0.
- reworked the latest `infortrend_chassis1`, `infortrend_disks1` and `infortrend_ldrives1` plugin checks to 
  - introduce performance data for all voltage, fan and temperature sensors and output the current values in the corresponding status fields.
  - correctly signal warn and critical levels.
  - make sure to correctly show all sensor values for dual controller systems which have SNMP sensors with the very same name throughout all controllers.

Due to the slight overhaul of the checkmk plugin and the changed service names the plugin version has been bumped to version 5.0.0.

### CODE REVIEW

**Comment by gurubert** [comment]
Hi @jens-maus ,

please base this pull request against the cmk2.3 branch of the repository.

**Comment by jens-maus** [comment]
@gurubert Sure, no problem. But would it not be easier/better to merge it into the cmk2.2 branch and then you cherry-pick the PR into cmk2.3 because the proposed changes are also compatible to CheckMK 2.2 AFAICS?

**Comment by gurubert** [comment]
There is no LegacyCheckDefinition in Checkmk 2.2 for example.

**Comment by jens-maus** [comment]
> There is no LegacyCheckDefinition in Checkmk 2.2 for example.

You are absolutely right. I missed that point. So I just rebased it to cmk2.3. So feel free to merge it now if you want.

**Pull request merged**
